### ISSUE TITLE
Translations missing in 2.1.x releases

### ISSUE THREAD

**Issue by spideyfusion** [gabe565/linuxserver-mod-vuetorrent#36] opened 2023-11-10 07:34 UTC
Looks like translations are no longer part of the [VueTorrent](https://github.com/WDaan/VueTorrent/) repository and are now fetched from Tolgee translation platform instead. You can check out the [PR](https://github.com/WDaan/VueTorrent/pull/1276) where the change was introduced.

As you can see, the translation files inside the repository are now [stubs](https://github.com/WDaan/VueTorrent/blob/v2.1.0/src/locales/en.json). This will cause the final mod Docker image to be without any translations.

**Comment by shad-lp** [comment] 2023-11-17 12:39
Hello, is that related to this kind of problem :

![image](https://github.com/gabe565/linuxserver-mod-vuetorrent/assets/43928955/1b051b5c-c56f-493f-b4a9-454fdad036e6)

Seems like, I would not want to open a new issue if it's related to yours.

**Comment by MattJeanes** [comment] 2023-11-17 13:00
If you are referring to the placeholder text like `NAVBAR.SIDE.CURRENT_SPEED.TITLE` at the top left, yes this is the cause of that issue

**Comment by gabe565** [comment] 2023-11-26 07:33
Sorry for the late reply, I'm going to swap the Docker build to download VueTorrent's release assets to fix this! Will keep you all posted on a fix.

**Comment by gabe565** [comment] 2023-11-26 07:41
@spideyfusion @shad-lp @MattJeanes I just pushed an updated that fixes this! Basically, the Docker build now pulls the VueTorrent release artifact instead of building from scratch. If you restart your qBittorrent containers, it should be fixed for you 🙂

**Closed** 2023-11-26 07:52 UTC
